### ISSUE TITLE
Allocation in every Format() call

### ISSUE THREAD

**Issue by ianwilkes** [lestrrat-go/strftime#25]
This is purely a performance issue, but a significant one. This library could be _much_ faster if it could be used in a zero-allocation way, writing into a buffer provided by the caller. Today, [this array](https://github.com/lestrrat-go/strftime/blob/master/strftime.go#L183
) leaks onto the heap because it's passed into `Write()`.

A simple fix would be to keep that array as a field of the `Strftime` struct, but then this method would be concurrency unsafe. (The `io.Writer` spec doesn't allow implementations to modify or retain references to the passed slice, so you can get away with re-using that buffer, but obviously not with concurrent use.)

I think a better approach would be an exported version of the internal `format` method - maybe just implement `Append` on Strftime. That way, the user can supply the buffer, and allocation only occurs if it's insufficient.

I'm happy to submit a PR if the approach sounds good.

**Comment by lestrrat** [comment]
Sure, feel free to submit a PR. One thing that bugged me was the naming. `strftimeThing.Append` would imply appending to the `strftimeThing`, so I would prefer `strftimeThing.FormatBuffer([]byte, time.Time)` or something like it instead.

Also, please make sure to benchmark the difference too. You say it's a "significant" performance issue without presenting any evidence. I will take your word for it, but I want the evidence included in the PR.

**Comment by ianwilkes** [comment]
Will do. Re: naming, the strconv library uses the `AppendFoo` naming convention for this kind of operation, so at least there's precedent. But FormatBuffer sounds fine.
