### ISSUE TITLE
unix time modifier

### ISSUE THREAD

**Issue by jftuga** [lestrrat-go/strftime#56]
Would you consider adding a [unix time](https://en.wikipedia.org/wiki/Unix_time) (aka epoch time) modifier? I've noticed that the`%s` modifier has not been allocated yet.

On MacOS and Linux:
```shell
$ date +"%s"
1731780106
```

If you like this idea, I'd be willing to work on a PR.

**Comment by lestrrat** [comment]
I think it's under the [extensions](https://github.com/lestrrat-go/strftime?tab=readme-ov-file#extensions--custom-specifications). IIRC I believe I made the supported specifications a strict subset of POSIX specs, just to remove any ambiguity -- for example, I didn't want to get into arguments about which ones to include and which ones to not.

**Comment by jftuga** [comment]
Thanks for pointing this out.
